#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
# autospec version: v5
# autospec commit: c02b2fe
#
Name     : pypi-glyphslib
Version  : 6.7.0
Release  : 20
URL      : https://files.pythonhosted.org/packages/75/cd/48e94d60ce0305dbb50346c9e8c2b6d250a51d37ec754849b87b52733ea4/glyphsLib-6.7.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/75/cd/48e94d60ce0305dbb50346c9e8c2b6d250a51d37ec754849b87b52733ea4/glyphsLib-6.7.0.tar.gz
Summary  : A bridge from Glyphs source files (.glyphs) to UFOs
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: pypi-glyphslib-bin = %{version}-%{release}
Requires: pypi-glyphslib-license = %{version}-%{release}
Requires: pypi-glyphslib-python = %{version}-%{release}
Requires: pypi-glyphslib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(appdirs)
BuildRequires : pypi(attrs)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
# glyphsLib.builder sketch
Here is an of overview of how `glyphsLib.builder` converts a Glyphs `GSFont` object into a set of UFO and Designspace files.

%package bin
Summary: bin components for the pypi-glyphslib package.
Group: Binaries
Requires: pypi-glyphslib-license = %{version}-%{release}

%description bin
bin components for the pypi-glyphslib package.


%package license
Summary: license components for the pypi-glyphslib package.
Group: Default

%description license
license components for the pypi-glyphslib package.


%package python
Summary: python components for the pypi-glyphslib package.
Group: Default
Requires: pypi-glyphslib-python3 = %{version}-%{release}

%description python
python components for the pypi-glyphslib package.


%package python3
Summary: python3 components for the pypi-glyphslib package.
Group: Default
Requires: python3-core
Provides: pypi(glyphslib)
Requires: pypi(appdirs)
Requires: pypi(attrs)
Requires: pypi(fonttools)
Requires: pypi(openstep_plist)
Requires: pypi(ufolib2)

%description python3
python3 components for the pypi-glyphslib package.


%prep
%setup -q -n glyphsLib-6.7.0
cd %{_builddir}/glyphsLib-6.7.0
pushd ..
cp -a glyphsLib-6.7.0 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1711505193
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-glyphslib
cp %{_builddir}/glyphsLib-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-glyphslib/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/glyphsLib-%{version}/Lib/glyphsLib/data/GlyphData_LICENSE %{buildroot}/usr/share/package-licenses/pypi-glyphslib/3d41934668818166425e722040957ab9410162f8 || :
cp %{_builddir}/glyphsLib-%{version}/tests/data/designspace/roboto/LICENSE %{buildroot}/usr/share/package-licenses/pypi-glyphslib/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
python3 -m installer --destdir=%{buildroot} dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
python3 -m installer --destdir=%{buildroot}-v3 dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glyphs2ufo
/usr/bin/ufo2glyphs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-glyphslib/3d41934668818166425e722040957ab9410162f8
/usr/share/package-licenses/pypi-glyphslib/7df059597099bb7dcf25d2a9aedfaf4465f72d8d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
