#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: pyproject
#
Name     : pypi-glyphslib
Version  : 6.2.4
Release  : 3
URL      : https://files.pythonhosted.org/packages/18/83/2940e5b124d20d9ed6aeb5125d61b08baa5bb585f242c6f83307339749c0/glyphsLib-6.2.4.tar.gz
Source0  : https://files.pythonhosted.org/packages/18/83/2940e5b124d20d9ed6aeb5125d61b08baa5bb585f242c6f83307339749c0/glyphsLib-6.2.4.tar.gz
Summary  : A bridge from Glyphs source files (.glyphs) to UFOs
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: pypi-glyphslib-bin = %{version}-%{release}
Requires: pypi-glyphslib-license = %{version}-%{release}
Requires: pypi-glyphslib-python = %{version}-%{release}
Requires: pypi-glyphslib-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(appdirs)
BuildRequires : pypi(attrs)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi(setuptools_scm)
BuildRequires : pypi(wheel)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
|CI Build Status| |PyPI Version| |Codecov| |Gitter Chat|
glyphsLib
=========
This Python 3.7+ library provides a bridge from Glyphs source files (.glyphs) to
UFOs and Designspace files via `defcon <https://github.com/typesupply/defcon/>`__ and `designspaceLib <https://github.com/fonttools/fonttools>`__.

%package bin
Summary: bin components for the pypi-glyphslib package.
Group: Binaries
Requires: pypi-glyphslib-license = %{version}-%{release}

%description bin
bin components for the pypi-glyphslib package.


%package license
Summary: license components for the pypi-glyphslib package.
Group: Default

%description license
license components for the pypi-glyphslib package.


%package python
Summary: python components for the pypi-glyphslib package.
Group: Default
Requires: pypi-glyphslib-python3 = %{version}-%{release}

%description python
python components for the pypi-glyphslib package.


%package python3
Summary: python3 components for the pypi-glyphslib package.
Group: Default
Requires: python3-core
Provides: pypi(glyphslib)
Requires: pypi(appdirs)
Requires: pypi(attrs)
Requires: pypi(fonttools)
Requires: pypi(openstep_plist)
Requires: pypi(ufolib2)

%description python3
python3 components for the pypi-glyphslib package.


%prep
%setup -q -n glyphsLib-6.2.4
cd %{_builddir}/glyphsLib-6.2.4
pushd ..
cp -a glyphsLib-6.2.4 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689176141
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pypi-glyphslib
cp %{_builddir}/glyphsLib-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/pypi-glyphslib/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
cp %{_builddir}/glyphsLib-%{version}/Lib/glyphsLib/data/GlyphData_LICENSE %{buildroot}/usr/share/package-licenses/pypi-glyphslib/3d41934668818166425e722040957ab9410162f8 || :
cp %{_builddir}/glyphsLib-%{version}/tests/data/designspace/roboto/LICENSE %{buildroot}/usr/share/package-licenses/pypi-glyphslib/7df059597099bb7dcf25d2a9aedfaf4465f72d8d || :
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/glyphs2ufo
/usr/bin/ufo2glyphs

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pypi-glyphslib/3d41934668818166425e722040957ab9410162f8
/usr/share/package-licenses/pypi-glyphslib/7df059597099bb7dcf25d2a9aedfaf4465f72d8d

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
